language: node_js

node_js:
  - "node"
warnings_are_errors: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "CB9oUTJpqDoj4XWxZIqbxN5RDEUBdp5W49EDY95RJp8H8JfS1mTxf4kXTnwUsXsAwEnrym25CLmKz0/ZFFdeBjbqDdJZIh2Tp1aMLpemm5QvcCLocnqCfw8nxUzmqeNsxr486e+/4f5iQv0xvCbMV/bJ6zwQ37HxfcXbg8QUuKlvPIOodVbFhFdGiR33HZaFi+EjkckP5xE7m/w7GmptodL3ehkwy8jf5RZIqvl+Ljj+zJ7SQxXhyGykVxf6aeZd6EicJZhW0Ie89lrea8HY4iltVQhXTxqctA5SYV8ube0J7J72Hz9kV6QpYAo4kx2Lw/KJ9TYn5GkTsmZtW8B6nJwvhysk6K/rJpidZU0YhvkColFSITcufHrX1DslbpmhlYATbN+Tpjpmq0au5sv1EsDZAQeXPUxJ9FTiu2nKYr8pDLEKqFZwKnecXhKlUBg3C/qSoMnr3xz3UurWJnJEdxly7Kw0/Y20Ua3VW6r1fFEPDOB2J3D6Uk3bBFMnXFp+2MSgzlrZC54rM+62SatoKkXyzpsiw8T7xiyZOOrKCrxsqrJw5zHfon0bnIwURmDoWuNYyAi5gV/stx6m09MbHgBOTYdjIYfOFvgZJWZu8kGaJNbryrk+FKaOMylDLmpI3q9BALlpL6hk+Vat/zE+72y63pS/nKkeGetn4hMvEU8="
